# This workflow will initiate a Veracode Static Analysis Pipeline scan, return a results.json and convert to SARIF for upload as a code scanning alert

name: Veracode Static Analysis Pipeline Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '40 21 * * 0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read
  checks: write
  pull-requests: write
  actions: read

jobs:
  # This workflow contains a job to build and submit pipeline scan, you will need to customize the build process accordingly and make sure the artifact you build is used as the file input to the pipeline scan file parameter
  pipeline-scan:
    # The type of runner that the job will run on
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it and copies all sources into ZIP file for submitting for analysis. Replace this section with your applications build steps
    - uses: actions/checkout@v4
      with:
        repository: ''

    - run: curl -fsS https://tools.veracode.com/veracode-cli/install | sh
    - run: ./veracode package -vas . -o verascan
    - run: zip -r verascan.zip verascan
        
    - name: pipeline-scan action step
      id: pipeline-scan
      uses: veracode/Veracode-pipeline-scan-action@esd-true
      with:
        vid: ${{ secrets.VERACODE_API_ID }}
        vkey: ${{ secrets.VERACODE_API_KEY }}
        file: "verascan.zip"
        debug: 1
      
    - name: Convert pipeline scan output to SARIF format
      id: convert
      uses: veracode/veracode-pipeline-scan-results-to-sarif@ff08ae5b45d5384cb4679932f184c013d34da9be
      with:
        pipeline-results-json: results.json
        
    - uses: github/codeql-action/upload-sarif@v4
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: veracode-results.sarif
    - uses: actions/upload-artifact@v4
      with:
        name: Veracode Pipeline-Scan Results-${{ github.run_attempt }}
        path: results.json 

  veracode-fix:
    runs-on: ubuntu-latest
    needs: pipeline-scan
    if: ${{ github.event_name == 'push' }}
    name: Veracode Fix
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: get flaw file
        uses: actions/download-artifact@v4
        with:
          name: Veracode Pipeline-Scan Results-${{ github.run_attempt }}
          
      - name: Create fixes from static findings
        id: convert
        uses: Veracode/veracode-fix@main
        with:
          inputFile: results.json
          vid: "${{ secrets.VERACODE_API_ID }}"
          vkey: "${{ secrets.VERACODE_API_KEY }}"
          source_base_path_1: "com/:src/main/java/com/"
          source_base_path_2: "WEB-INF:src/main/webapp/WEB-INF"
          debug: true
          createPR: true
          codeSuggestion: false
          language: java
          prComment: false
          fixType: batch
